import type { Currency } from './types';

export const currencies: Currency[] = [
  // Major Global Currencies
  { code: 'USD', name: 'US Dollar', symbol: '$', symbolPosition: 'before', flag: '🇺🇸', decimalDigits: 2 },
  { code: 'EUR', name: 'Euro', symbol: '€', symbolPosition: 'before', flag: '🇪🇺', decimalDigits: 2 },
  { code: 'GBP', name: 'British Pound', symbol: '£', symbolPosition: 'before', flag: '🇬🇧', decimalDigits: 2 },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', symbolPosition: 'before', flag: '🇯🇵', decimalDigits: 0 },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', symbolPosition: 'before', flag: '🇨🇳', decimalDigits: 2 },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', symbolPosition: 'after', flag: '🇨🇭', decimalDigits: 2 },
  { code: 'CAD', name: 'Canadian Dollar', symbol: '$', symbolPosition: 'before', flag: '🇨🇦', decimalDigits: 2 },
  { code: 'AUD', name: 'Australian Dollar', symbol: '$', symbolPosition: 'before', flag: '🇦🇺', decimalDigits: 2 },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: '$', symbolPosition: 'before', flag: '🇳🇿', decimalDigits: 2 },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: '$', symbolPosition: 'before', flag: '🇭🇰', decimalDigits: 2 },
  { code: 'SGD', name: 'Singapore Dollar', symbol: '$', symbolPosition: 'before', flag: '🇸🇬', decimalDigits: 2 },

  // Asian Currencies
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', symbolPosition: 'before', flag: '🇮🇳', decimalDigits: 2 },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', symbolPosition: 'before', flag: '🇵🇰', decimalDigits: 2 },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', symbolPosition: 'before', flag: '🇧🇩', decimalDigits: 2 },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs', symbolPosition: 'before', flag: '🇱🇰', decimalDigits: 2 },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: 'रु', symbolPosition: 'before', flag: '🇳🇵', decimalDigits: 2 },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', symbolPosition: 'before', flag: '🇮🇩', decimalDigits: 2 },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', symbolPosition: 'before', flag: '🇲🇾', decimalDigits: 2 },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', symbolPosition: 'before', flag: '🇹🇭', decimalDigits: 2 },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', symbolPosition: 'before', flag: '🇵🇭', decimalDigits: 2 },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', symbolPosition: 'after', flag: '🇻🇳', decimalDigits: 0 },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩', symbolPosition: 'before', flag: '🇰🇷', decimalDigits: 0 },
  { code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$', symbolPosition: 'before', flag: '🇹🇼', decimalDigits: 2 },
  { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', symbolPosition: 'before', flag: '🇲🇲', decimalDigits: 2 },
  { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', symbolPosition: 'after', flag: '🇰🇭', decimalDigits: 2 },
  { code: 'LAK', name: 'Lao Kip', symbol: '₭', symbolPosition: 'before', flag: '🇱🇦', decimalDigits: 2 },
  { code: 'BND', name: 'Brunei Dollar', symbol: '$', symbolPosition: 'before', flag: '🇧🇳', decimalDigits: 2 },
  { code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP$', symbolPosition: 'before', flag: '🇲🇴', decimalDigits: 2 },
  { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', symbolPosition: 'after', flag: '🇦🇫', decimalDigits: 2 },

  // Middle Eastern Currencies
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', symbolPosition: 'before', flag: '🇦🇪', decimalDigits: 2 },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', symbolPosition: 'before', flag: '🇸🇦', decimalDigits: 2 },
  { code: 'QAR', name: 'Qatari Riyal', symbol: 'ر.ق', symbolPosition: 'before', flag: '🇶🇦', decimalDigits: 2 },
  { code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.', symbolPosition: 'before', flag: '🇴🇲', decimalDigits: 3 },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', symbolPosition: 'before', flag: '🇰🇼', decimalDigits: 3 },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب', symbolPosition: 'before', flag: '🇧🇭', decimalDigits: 3 },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'JD', symbolPosition: 'after', flag: '🇯🇴', decimalDigits: 3 },
  { code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل', symbolPosition: 'before', flag: '🇱🇧', decimalDigits: 2 },
  { code: 'SYP', name: 'Syrian Pound', symbol: '£', symbolPosition: 'before', flag: '🇸🇾', decimalDigits: 2 },
  { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د', symbolPosition: 'before', flag: '🇮🇶', decimalDigits: 3 },
  { code: 'IRR', name: 'Iranian Rial', symbol: '﷼', symbolPosition: 'before', flag: '🇮🇷', decimalDigits: 2 },
  { code: 'YER', name: 'Yemeni Rial', symbol: '﷼', symbolPosition: 'before', flag: '🇾🇪', decimalDigits: 2 },
  { code: 'ILS', name: 'Israeli New Shekel', symbol: '₪', symbolPosition: 'before', flag: '🇮🇱', decimalDigits: 2 },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', symbolPosition: 'before', flag: '🇹🇷', decimalDigits: 2 },

  // African Currencies
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', symbolPosition: 'before', flag: '🇿🇦', decimalDigits: 2 },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', symbolPosition: 'before', flag: '🇳🇬', decimalDigits: 2 },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', symbolPosition: 'before', flag: '🇰🇪', decimalDigits: 2 },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: 'GH₵', symbolPosition: 'before', flag: '🇬🇭', decimalDigits: 2 },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', symbolPosition: 'before', flag: '🇪🇬', decimalDigits: 2 },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.', symbolPosition: 'after', flag: '🇲🇦', decimalDigits: 2 },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت', symbolPosition: 'after', flag: '🇹🇳', decimalDigits: 3 },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج', symbolPosition: 'after', flag: '🇩🇿', decimalDigits: 2 },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', symbolPosition: 'before', flag: '🇪🇹', decimalDigits: 2 },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', symbolPosition: 'before', flag: '🇺🇬', decimalDigits: 0 },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', symbolPosition: 'before', flag: '🇹🇿', decimalDigits: 2 },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', symbolPosition: 'before', flag: '🇿🇲', decimalDigits: 2 },
  { code: 'BWP', name: 'Botswana Pula', symbol: 'P', symbolPosition: 'before', flag: '🇧🇼', decimalDigits: 2 },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', symbolPosition: 'before', flag: '🇲🇺', decimalDigits: 2 },
  { code: 'SCR', name: 'Seychellois Rupee', symbol: '₨', symbolPosition: 'before', flag: '🇸🇨', decimalDigits: 2 },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'FRw', symbolPosition: 'after', flag: '🇷🇼', decimalDigits: 0 },
  { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', symbolPosition: 'before', flag: '🇦🇴', decimalDigits: 2 },
  { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', symbolPosition: 'before', flag: '🇲🇿', decimalDigits: 2 },
  { code: 'LYD', name: 'Libyan Dinar', symbol: 'ل.د', symbolPosition: 'after', flag: '🇱🇾', decimalDigits: 3 },
  { code: 'SDG', name: 'Sudanese Pound', symbol: 'ج.س.', symbolPosition: 'before', flag: '🇸🇩', decimalDigits: 2 },
  { code: 'SOS', name: 'Somali Shilling', symbol: 'S', symbolPosition: 'before', flag: '🇸🇴', decimalDigits: 2 },
  { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', symbolPosition: 'after', flag: '🇬🇲', decimalDigits: 2 },
  { code: 'SLL', name: 'Sierra Leonean Leone', symbol: 'Le', symbolPosition: 'before', flag: '🇸🇱', decimalDigits: 2 },
  { code: 'LRD', name: 'Liberian Dollar', symbol: '$', symbolPosition: 'before', flag: '🇱🇷', decimalDigits: 2 },
  { code: 'CDF', name: 'Congolese Franc', symbol: 'FC', symbolPosition: 'after', flag: '🇨🇩', decimalDigits: 2 },
  { code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA', symbolPosition: 'after', flag: '🇨🇫', decimalDigits: 0 },
  { code: 'XOF', name: 'West African CFA Franc', symbol: 'CFA', symbolPosition: 'after', flag: '🇸🇳', decimalDigits: 0 },

  // European Currencies
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽', symbolPosition: 'after', flag: '🇷🇺', decimalDigits: 2 },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', symbolPosition: 'after', flag: '🇺🇦', decimalDigits: 2 },
  { code: 'PLN', name: 'Polish Złoty', symbol: 'zł', symbolPosition: 'after', flag: '🇵🇱', decimalDigits: 2 },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', symbolPosition: 'after', flag: '🇨🇿', decimalDigits: 2 },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', symbolPosition: 'after', flag: '🇭🇺', decimalDigits: 2 },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei', symbolPosition: 'after', flag: '🇷🇴', decimalDigits: 2 },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', symbolPosition: 'after', flag: '🇧🇬', decimalDigits: 2 },
  { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn', symbolPosition: 'after', flag: '🇭🇷', decimalDigits: 2 },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', symbolPosition: 'after', flag: '🇸🇪', decimalDigits: 2 },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', symbolPosition: 'after', flag: '🇳🇴', decimalDigits: 2 },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', symbolPosition: 'after', flag: '🇩🇰', decimalDigits: 2 },
  { code: 'ISK', name: 'Icelandic Króna', symbol: 'kr', symbolPosition: 'after', flag: '🇮🇸', decimalDigits: 0 },
  { code: 'ALL', name: 'Albanian Lek', symbol: 'L', symbolPosition: 'before', flag: '🇦🇱', decimalDigits: 2 },
  { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM', symbolPosition: 'after', flag: '🇧🇦', decimalDigits: 2 },
  { code: 'MKD', name: 'Macedonian Denar', symbol: 'ден', symbolPosition: 'after', flag: '🇲🇰', decimalDigits: 2 },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'дин.', symbolPosition: 'after', flag: '🇷🇸', decimalDigits: 2 },
  { code: 'MDL', name: 'Moldovan Leu', symbol: 'L', symbolPosition: 'after', flag: '🇲🇩', decimalDigits: 2 },
  { code: 'GEL', name: 'Georgian Lari', symbol: '₾', symbolPosition: 'after', flag: '🇬🇪', decimalDigits: 2 },
  { code: 'AMD', name: 'Armenian Dram', symbol: '֏', symbolPosition: 'after', flag: '🇦🇲', decimalDigits: 2 },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', symbolPosition: 'after', flag: '🇦🇿', decimalDigits: 2 },
  { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', symbolPosition: 'after', flag: '🇧🇾', decimalDigits: 2 },
  
  // Latin American Currencies
  { code: 'MXN', name: 'Mexican Peso', symbol: '$', symbolPosition: 'before', flag: '🇲🇽', decimalDigits: 2 },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', symbolPosition: 'before', flag: '🇧🇷', decimalDigits: 2 },
  { code: 'ARS', name: 'Argentine Peso', symbol: '$', symbolPosition: 'before', flag: '🇦🇷', decimalDigits: 2 },
  { code: 'CLP', name: 'Chilean Peso', symbol: '$', symbolPosition: 'before', flag: '🇨🇱', decimalDigits: 0 },
  { code: 'COP', name: 'Colombian Peso', symbol: '$', symbolPosition: 'before', flag: '🇨🇴', decimalDigits: 2 },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/', symbolPosition: 'before', flag: '🇵🇪', decimalDigits: 2 },
  { code: 'VES', name: 'Venezuelan Bolívar', symbol: 'Bs.', symbolPosition: 'before', flag: '🇻🇪', decimalDigits: 2 },
  { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs.', symbolPosition: 'before', flag: '🇧🇴', decimalDigits: 2 },
  { code: 'PYG', name: 'Paraguayan Guaraní', symbol: '₲', symbolPosition: 'before', flag: '🇵🇾', decimalDigits: 0 },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U', symbolPosition: 'before', flag: '🇺🇾', decimalDigits: 2 },
  { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡', symbolPosition: 'before', flag: '🇨🇷', decimalDigits: 2 },
  { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', symbolPosition: 'before', flag: '🇬🇹', decimalDigits: 2 },
  { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', symbolPosition: 'before', flag: '🇭🇳', decimalDigits: 2 },
  { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$', symbolPosition: 'before', flag: '🇳🇮', decimalDigits: 2 },
  { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', symbolPosition: 'before', flag: '🇵🇦', decimalDigits: 2 },
  { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$', symbolPosition: 'before', flag: '🇩🇴', decimalDigits: 2 },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$', symbolPosition: 'before', flag: '🇯🇲', decimalDigits: 2 },
  { code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: 'TT$', symbolPosition: 'before', flag: '🇹🇹', decimalDigits: 2 },
  { code: 'BBD', name: 'Barbadian Dollar', symbol: '$', symbolPosition: 'before', flag: '🇧🇧', decimalDigits: 2 },
  { code: 'BSD', name: 'Bahamian Dollar', symbol: '$', symbolPosition: 'before', flag: '🇧🇸', decimalDigits: 2 },
  { code: 'XCD', name: 'East Caribbean Dollar', symbol: '$', symbolPosition: 'before', flag: '🇦🇬', decimalDigits: 2 },

  // Pacific & Oceania
  { code: 'FJD', name: 'Fijian Dollar', symbol: '$', symbolPosition: 'before', flag: '🇫🇯', decimalDigits: 2 },
  { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', symbolPosition: 'before', flag: '🇵🇬', decimalDigits: 2 },
  { code: 'WST', name: 'Samoan Tālā', symbol: 'WS$', symbolPosition: 'before', flag: '🇼🇸', decimalDigits: 2 },
  { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$', symbolPosition: 'before', flag: '🇹🇴', decimalDigits: 2 },
  { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT', symbolPosition: 'after', flag: '🇻🇺', decimalDigits: 0 },
  { code: 'SBD', name: 'Solomon Islands Dollar', symbol: '$', symbolPosition: 'before', flag: '🇸🇧', decimalDigits: 2 },
  
  // Cryptocurrencies
  { code: 'BTC', name: 'Bitcoin', symbol: '₿', symbolPosition: 'after', flag: '🪙', decimalDigits: 8 },
  { code: 'ETH', name: 'Ethereum', symbol: 'Ξ', symbolPosition: 'after', flag: '🪙', decimalDigits: 8 },
  { code: 'USDT', name: 'Tether', symbol: '₮', symbolPosition: 'after', flag: '🪙', decimalDigits: 2 },
  { code: 'USDC', name: 'USD Coin', symbol: '$', symbolPosition: 'before', flag: '🪙', decimalDigits: 2 },
];
